# Generated by Django 2.0.4 on 2018-05-03 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='My', max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, default='My', max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=255, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('subjects', models.CharField(blank=True, choices=[('01', 'Math'), ('02', 'English'), ('03', 'Physics'), ('04', 'Information Technology')], max_length=255, null=True)),
                ('location', models.CharField(blank=True, choices=[('01', 'St. Joseph'), ('02', 'San Juan')], max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
